[versions]
hazelcast-spring = "5.4.0"
hazelcast-hibernate53 = "5.1.0"
jacoco = "0.8.12"
checkstyle = "10.17.0"
# jhipster-needle-gradle-dependency-catalog-version - JHipster will add additional versions for convention plugins heref

[libraries]
jhipster-framework = { module = "tech.jhipster:jhipster-framework", version = "8.6.0" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version = "2023.0.2" }
springdoc-openapi-starter-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version = "2.5.0" }
hazelcast-hibernate53 = { module = "com.hazelcast:hazelcast-hibernate53", version = "5.1.0" }
hazelcast-spring = { module = "com.hazelcast:hazelcast-spring", version = "5.4.0" }
# jhipster-needle-gradle-dependency-catalog-libraries - JHipster will add additional libraries versions

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.1" }
# jhipster-needle-gradle-dependency-catalog-plugins - JHipster will add additional plugins versions
