package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DanhMucLoaiTaiSanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiTaiSanAllPropertiesEquals(DanhMucLoaiTaiSan expected, DanhMucLoaiTaiSan actual) {
        assertDanhMucLoaiTaiSanAutoGeneratedPropertiesEquals(expected, actual);
        assertDanhMucLoaiTaiSanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiTaiSanAllUpdatablePropertiesEquals(DanhMucLoaiTaiSan expected, DanhMucLoaiTaiSan actual) {
        assertDanhMucLoaiTaiSanUpdatableFieldsEquals(expected, actual);
        assertDanhMucLoaiTaiSanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiTaiSanAutoGeneratedPropertiesEquals(DanhMucLoaiTaiSan expected, DanhMucLoaiTaiSan actual) {
        assertThat(expected)
            .as("Verify DanhMucLoaiTaiSan auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiTaiSanUpdatableFieldsEquals(DanhMucLoaiTaiSan expected, DanhMucLoaiTaiSan actual) {
        assertThat(expected)
            .as("Verify DanhMucLoaiTaiSan relevant properties")
            .satisfies(e -> assertThat(e.getIdLoaiTs()).as("check idLoaiTs").isEqualTo(actual.getIdLoaiTs()))
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()))
            .satisfies(e -> assertThat(e.getSearchStr()).as("check searchStr").isEqualTo(actual.getSearchStr()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDanhMucLoaiTaiSanUpdatableRelationshipsEquals(DanhMucLoaiTaiSan expected, DanhMucLoaiTaiSan actual) {}
}
