package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SoHuuTheoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoHuuTheoAllPropertiesEquals(SoHuuTheo expected, SoHuuTheo actual) {
        assertSoHuuTheoAutoGeneratedPropertiesEquals(expected, actual);
        assertSoHuuTheoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoHuuTheoAllUpdatablePropertiesEquals(SoHuuTheo expected, SoHuuTheo actual) {
        assertSoHuuTheoUpdatableFieldsEquals(expected, actual);
        assertSoHuuTheoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoHuuTheoAutoGeneratedPropertiesEquals(SoHuuTheo expected, SoHuuTheo actual) {
        assertThat(expected)
            .as("Verify SoHuuTheo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoHuuTheoUpdatableFieldsEquals(SoHuuTheo expected, SoHuuTheo actual) {
        assertThat(expected)
            .as("Verify SoHuuTheo relevant properties")
            .satisfies(e -> assertThat(e.getIdSoHuu()).as("check idSoHuu").isEqualTo(actual.getIdSoHuu()))
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getTenGcn()).as("check tenGcn").isEqualTo(actual.getTenGcn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSoHuuTheoUpdatableRelationshipsEquals(SoHuuTheo expected, SoHuuTheo actual) {}
}
