package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaisannhadatidAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisannhadatidAllPropertiesEquals(Taisannhadatid expected, Taisannhadatid actual) {
        assertTaisannhadatidAutoGeneratedPropertiesEquals(expected, actual);
        assertTaisannhadatidAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisannhadatidAllUpdatablePropertiesEquals(Taisannhadatid expected, Taisannhadatid actual) {
        assertTaisannhadatidUpdatableFieldsEquals(expected, actual);
        assertTaisannhadatidUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisannhadatidAutoGeneratedPropertiesEquals(Taisannhadatid expected, Taisannhadatid actual) {
        assertThat(expected)
            .as("Verify Taisannhadatid auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisannhadatidUpdatableFieldsEquals(Taisannhadatid expected, Taisannhadatid actual) {
        assertThat(expected)
            .as("Verify Taisannhadatid relevant properties")
            .satisfies(e -> assertThat(e.getIdTaiSan()).as("check idTaiSan").isEqualTo(actual.getIdTaiSan()))
            .satisfies(e -> assertThat(e.getThongTinTs()).as("check thongTinTs").isEqualTo(actual.getThongTinTs()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisannhadatidUpdatableRelationshipsEquals(Taisannhadatid expected, Taisannhadatid actual) {}
}
