package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaisanSaiQsddDgcAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiQsddDgcAllPropertiesEquals(TaisanSaiQsddDgc expected, TaisanSaiQsddDgc actual) {
        assertTaisanSaiQsddDgcAutoGeneratedPropertiesEquals(expected, actual);
        assertTaisanSaiQsddDgcAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiQsddDgcAllUpdatablePropertiesEquals(TaisanSaiQsddDgc expected, TaisanSaiQsddDgc actual) {
        assertTaisanSaiQsddDgcUpdatableFieldsEquals(expected, actual);
        assertTaisanSaiQsddDgcUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiQsddDgcAutoGeneratedPropertiesEquals(TaisanSaiQsddDgc expected, TaisanSaiQsddDgc actual) {
        assertThat(expected)
            .as("Verify TaisanSaiQsddDgc auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiQsddDgcUpdatableFieldsEquals(TaisanSaiQsddDgc expected, TaisanSaiQsddDgc actual) {
        assertThat(expected)
            .as("Verify TaisanSaiQsddDgc relevant properties")
            .satisfies(e -> assertThat(e.getIdMaster()).as("check idMaster").isEqualTo(actual.getIdMaster()))
            .satisfies(e -> assertThat(e.getNoiCapQsdd()).as("check noiCapQsdd").isEqualTo(actual.getNoiCapQsdd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiQsddDgcUpdatableRelationshipsEquals(TaisanSaiQsddDgc expected, TaisanSaiQsddDgc actual) {}
}
