package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaisanSaiDgcAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiDgcAllPropertiesEquals(TaisanSaiDgc expected, TaisanSaiDgc actual) {
        assertTaisanSaiDgcAutoGeneratedPropertiesEquals(expected, actual);
        assertTaisanSaiDgcAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiDgcAllUpdatablePropertiesEquals(TaisanSaiDgc expected, TaisanSaiDgc actual) {
        assertTaisanSaiDgcUpdatableFieldsEquals(expected, actual);
        assertTaisanSaiDgcUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiDgcAutoGeneratedPropertiesEquals(TaisanSaiDgc expected, TaisanSaiDgc actual) {
        assertThat(expected)
            .as("Verify TaisanSaiDgc auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiDgcUpdatableFieldsEquals(TaisanSaiDgc expected, TaisanSaiDgc actual) {
        assertThat(expected)
            .as("Verify TaisanSaiDgc relevant properties")
            .satisfies(e -> assertThat(e.getIdMaster()).as("check idMaster").isEqualTo(actual.getIdMaster()))
            .satisfies(e -> assertThat(e.getThongTinTs()).as("check thongTinTs").isEqualTo(actual.getThongTinTs()))
            .satisfies(e -> assertThat(e.getThongTinTsDung()).as("check thongTinTsDung").isEqualTo(actual.getThongTinTsDung()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaisanSaiDgcUpdatableRelationshipsEquals(TaisanSaiDgc expected, TaisanSaiDgc actual) {}
}
