package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ThuaTachAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThuaTachAllPropertiesEquals(ThuaTach expected, ThuaTach actual) {
        assertThuaTachAutoGeneratedPropertiesEquals(expected, actual);
        assertThuaTachAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThuaTachAllUpdatablePropertiesEquals(ThuaTach expected, ThuaTach actual) {
        assertThuaTachUpdatableFieldsEquals(expected, actual);
        assertThuaTachUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThuaTachAutoGeneratedPropertiesEquals(ThuaTach expected, ThuaTach actual) {
        assertThat(expected)
            .as("Verify ThuaTach auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThuaTachUpdatableFieldsEquals(ThuaTach expected, ThuaTach actual) {
        assertThat(expected)
            .as("Verify ThuaTach relevant properties")
            .satisfies(e -> assertThat(e.getIdThuaTach()).as("check idThuaTach").isEqualTo(actual.getIdThuaTach()))
            .satisfies(e -> assertThat(e.getIdTaiSan()).as("check idTaiSan").isEqualTo(actual.getIdTaiSan()))
            .satisfies(e -> assertThat(e.getThongTinThuaTach()).as("check thongTinThuaTach").isEqualTo(actual.getThongTinThuaTach()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertThuaTachUpdatableRelationshipsEquals(ThuaTach expected, ThuaTach actual) {}
}
