package vn.vnpt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TinhTrangTaiSanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTinhTrangTaiSanAllPropertiesEquals(TinhTrangTaiSan expected, TinhTrangTaiSan actual) {
        assertTinhTrangTaiSanAutoGeneratedPropertiesEquals(expected, actual);
        assertTinhTrangTaiSanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTinhTrangTaiSanAllUpdatablePropertiesEquals(TinhTrangTaiSan expected, TinhTrangTaiSan actual) {
        assertTinhTrangTaiSanUpdatableFieldsEquals(expected, actual);
        assertTinhTrangTaiSanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTinhTrangTaiSanAutoGeneratedPropertiesEquals(TinhTrangTaiSan expected, TinhTrangTaiSan actual) {
        assertThat(expected)
            .as("Verify TinhTrangTaiSan auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTinhTrangTaiSanUpdatableFieldsEquals(TinhTrangTaiSan expected, TinhTrangTaiSan actual) {
        assertThat(expected)
            .as("Verify TinhTrangTaiSan relevant properties")
            .satisfies(e -> assertThat(e.getIdTinhTrang()).as("check idTinhTrang").isEqualTo(actual.getIdTinhTrang()))
            .satisfies(e -> assertThat(e.getDienGiai()).as("check dienGiai").isEqualTo(actual.getDienGiai()))
            .satisfies(e -> assertThat(e.getTrangThai()).as("check trangThai").isEqualTo(actual.getTrangThai()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTinhTrangTaiSanUpdatableRelationshipsEquals(TinhTrangTaiSan expected, TinhTrangTaiSan actual) {}
}
